# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn run build

      - run:
          name: Extract version from package.json
          command: |
            echo 'VERSION="$(npm --loglevel silent run get-version)"' >> $BASH_ENV
            source $BASH_ENV

      - setup_remote_docker

      - run:
          name: Build Docker image
          command: docker build -t nbbdog11/http-response-tester:$VERSION .

  publish_image:
    docker:
      - image: circleci/node:9

    working_directory: ~/repo

    steps:
      - run:
          name: Publish to Docker Hub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push nbbdog11/http-response-tester:$VERSION

workflows:
  version: 2
  build_and_publish:
    jobs:
      - build
      - publish_image:
          requires:
            - build
          filters:
            branches:
              only: master